show_artists:
    path: /artists
    controller: App\Controller\ArtistController::showArtists
show_artist:
    path: /artist/{token}
    controller: App\Controller\ArtistController::showArtist
show_album:
    path: /albums/{token}
    controller: App\Controller\AlbumController::showAlbum